name: CI
on: [push]
jobs:
  build:
   contents: read
  pull-requests: write
  name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
  runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['latest']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ 'latest' }}
      - name: Install deps and build
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
      - name: Build yarn
      - uses: actions/cache@v3 
  id: cache
  with:
    path: path/to/dependencies
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
